name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Configure git
        run: |
          git config --global user.name 'Mike Chabot'
          git config --global user.email 'mikechabot@users.noreply.github.com'
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump version
        run: |
          pnpm version prerelease
          git add .

      # Use "--no-git-checks" on publish since pnpm thinks the branch is unclean due to the push above
      - name: Publish to npm
        run: |
          pnpm pack
          pnpm publish --no-git-checks --access public

      # See https://github.com/ad-m/github-push-action
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


